# Generated by Django 5.1.2 on 2024-10-30 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, unique=True, verbose_name='Заголовок')),
                ('date', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('shortDescription', models.CharField(max_length=10000, verbose_name='Короткое описание')),
                ('content', models.TextField(verbose_name='Контент')),
            ],
        ),
    ]
