# Generated by Django 5.1.2 on 2024-10-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='clickCount',
            field=models.IntegerField(default=0, verbose_name='Количество переходов'),
        ),
    ]
